### ISSUE TITLE
Bulk and signature data

### ISSUE THREAD

**Issue by j-bac** [BoevaLab/CanSig-benchmark#1]
Many thanks for the insightful study and well-organized repo !

I downloaded the single cell datasets following the instructions and python script. However I am not sure how to obtain the bulk data and signatures. e.g. in `configs/config_gbm_subsample.yml`:

```
    bulk_path: TCGA_data/GBM/GBM_gex_fpkm_uq.csv
    signatures:
      - neftel_4
      - neftel_6




signatures:
  neftel_4:
    annotation_path: annotations/Neftel_4.csv
    scoring_scenario: neftel_smartseq2_brain
    n_cluster: 4

  neftel_6:
    annotation_path: annotations/Neftel_6.csv
    scoring_scenario: neftel_smartseq2_brain
    n_cluster: 6
```
